name: sample test pipeline
#run-name: "Triggered ${{ github.event_name }} by ${{ github.actor }} with ${{ github.actor_id}}"
on:
  push:
    branches:
      - develop
      - feature/*
  workflow_dispatch:
    inputs:
      user_stmt:
        type: string
        description: asking user input to print
        required: false
      user_number:
        type: string
        description: enter whole number
        required: true
      
jobs:
  my_job:
    name: personal-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout curent repo
        uses: actions/checkout@v4
      - name: print current workspace repo
        run: |
          echo $GITHUB_WORKSPACE
          python3 test3.py $user_number

